<?php

return [
    'Afghanistan' => ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz', 'Ghazni', 'Balkh', 'Baghlan', 'Gardez'],    'Albania' => ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier'],
    'Algeria' => ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida'],
    'Andorra' => ['Andorra la Vella', 'Escaldes-Engordany', 'Encamp', 'Sant Julià de Lòria', 'La Massana'],
    'Angola' => ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito'],
    'Antigua and Barbuda' => ['St. John\'s', 'All Saints', 'Liberta', 'Potters Village', 'Bolans'],
    'Argentina' => ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata', 'San Miguel de Tucumán', 'Mar del Plata', 'Salta'],
    'Armenia' => ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Abovyan'],
    'Australia' => ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Hobart', 'Darwin', 'Cairns', 'Newcastle', 'Geelong', 'Townsville'],    'Austria' => ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
    'Azerbaijan' => ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Shirvan'],
    'Bahamas' => ['Nassau', 'Freeport', 'West End', 'Coopers Town', 'Marsh Harbour'],
    'Bahrain' => ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'A\'ali'],
    'Bangladesh' => ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Rangpur', 'Comilla', 'Narayanganj', 'Gazipur'],    'Barbados' => ['Bridgetown', 'Speightstown', 'Oistins', 'Bathsheba', 'Holetown'],
    'Belarus' => ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno'],
    'Belgium' => ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège'],
    'Belize' => ['Belize City', 'San Ignacio', 'Belmopan', 'Orange Walk Town', 'Corozal Town'],
    'Benin' => ['Cotonou', 'Porto-Novo', 'Parakou', 'Djougou', 'Bohicon'],
    'Bhutan' => ['Thimphu', 'Phuntsholing', 'Punakha', 'Samdrup Jongkhar', 'Geylegphug'],
    'Bolivia' => ['Santa Cruz de la Sierra', 'El Alto', 'La Paz', 'Cochabamba', 'Oruro'],
    'Bosnia and Herzegovina' => ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'],
    'Botswana' => ['Gaborone', 'Francistown', 'Molepolole', 'Serowe', 'Selibe Phikwe'],
    'Brazil' => ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belém', 'Goiânia'],    'Brunei' => ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Bangar'],
    'Bulgaria' => ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'],
    'Burkina Faso' => ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya'],
    'Burundi' => ['Bujumbura', 'Gitega', 'Muyinga', 'Ngozi', 'Ruyigi'],
    'Cabo Verde' => ['Praia', 'Mindelo', 'Espargos', 'Assomada', 'Pedra Badejo'],
    'Cambodia' => ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham'],
    'Cameroon' => ['Douala', 'Yaoundé', 'Bamenda', 'Bafoussam', 'Garoua'],
    'Canada' => ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Victoria', 'Halifax'],    'Central African Republic' => ['Bangui', 'Bimbo', 'Berbérati', 'Carnot', 'Bambari'],
    'Chad' => ['N\'Djamena', 'Moundou', 'Sarh', 'Abéché', 'Kélo'],
    'Chile' => ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta'],
    'China' => ['Shanghai', 'Beijing', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Tianjin', 'Wuhan', 'Xi\'an', 'Dongguan', 'Foshan', 'Hangzhou', 'Nanjing', 'Shenyang', 'Chongqing'],    'Colombia' => ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'],
    'Comoros' => ['Moroni', 'Mutsamudu', 'Fomboni', 'Domoni', 'Tsembehou'],
    'Congo' => ['Brazzaville', 'Pointe-Noire', 'Dolisie', 'Nkayi', 'Owando'],
    'Costa Rica' => ['San José', 'Puerto Limón', 'San Francisco', 'Alajuela', 'Liberia'],
    'Croatia' => ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'],
    'Cuba' => ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
    'Cyprus' => ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta', 'Paphos'],
    'Czech Republic' => ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec'],
    'Democratic Republic of the Congo' => ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'],
    'Denmark' => ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
    'Djibouti' => ['Djibouti City', 'Ali Sabieh', 'Tadjoura', 'Obock', 'Dikhil'],
    'Dominica' => ['Roseau', 'Portsmouth', 'Canefield', 'Marigot', 'Salisbury'],
    'Dominican Republic' => ['Santo Domingo', 'Santiago de los Caballeros', 'San Pedro de Macorís', 'La Romana', 'Los Alcarrizos'],
    'Ecuador' => ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala'],
    'Egypt' => ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Aswan'],
    'El Salvador' => ['San Salvador', 'Soyapango', 'Santa Ana', 'San Miguel', 'Mejicanos'],
    'Equatorial Guinea' => ['Malabo', 'Bata', 'Ebebiyín', 'Aconibe', 'Añisok'],
    'Eritrea' => ['Asmara', 'Keren', 'Massawa', 'Assab', 'Mendefera'],
    'Estonia' => ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve'],
    'Eswatini' => ['Mbabane', 'Manzini', 'Big Bend', 'Malkerns', 'Nhlangano'],
    'Ethiopia' => ['Addis Ababa', 'Dire Dawa', 'Mek\'ele', 'Gondar', 'Bahir Dar'],
    'Fiji' => ['Suva', 'Lautoka', 'Nadi', 'Labasa', 'Ba'],
    'Finland' => ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'],
    'France' => ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre'],    'Gabon' => ['Libreville', 'Port-Gentil', 'Franceville', 'Oyem', 'Moanda'],
    'Gambia' => ['Banjul', 'Serekunda', 'Brikama', 'Bakau', 'Farafenni'],
    'Georgia' => ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi', 'Gori'],
    'Germany' => ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden', 'Hanover'],    'Ghana' => ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Ashaiman'],
    'Greece' => ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Ioannina'],
    'Grenada' => ['St. George\'s', 'Gouyave', 'Grenville', 'Victoria', 'Sauteurs'],
    'Guatemala' => ['Guatemala City', 'Mixco', 'Villa Nueva', 'Petapa', 'Quetzaltenango'],
    'Guinea' => ['Conakry', 'Nzérékoré', 'Kankan', 'Kindia', 'Siguiri'],
    'Guinea-Bissau' => ['Bissau', 'Bafatá', 'Gabú', 'Bissorã', 'Bolama'],
    'Guyana' => ['Georgetown', 'Linden', 'New Amsterdam', 'Anna Regina', 'Bartica'],
    'Haiti' => ['Port-au-Prince', 'Carrefour', 'Delmas', 'Pétion-Ville', 'Cité Soleil'],
    'Honduras' => ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso'],
    'Hungary' => ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs'],
    'Iceland' => ['Reykjavík', 'Kópavogur', 'Hafnarfjörður', 'Akureyri', 'Reykjanesbær'],
    'India' => ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam'],    'Indonesia' => ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Palembang', 'Makassar', 'Batam'],
    'Iran' => ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz', 'Qom', 'Ahvaz', 'Kermanshah', 'Urmia', 'Rasht', 'Zahedan'],    'Iraq' => ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk'],
    'Ireland' => ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'],
    'Israel' => ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva'],
    'Italy' => ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania', 'Venice', 'Verona'],    'Jamaica' => ['Kingston', 'Portmore', 'Spanish Town', 'Montego Bay', 'May Pen'],
    'Japan' => ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Kobe', 'Kyoto', 'Fukuoka', 'Kawasaki', 'Saitama', 'Hiroshima', 'Sendai'],    'Jordan' => ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Aqaba'],
    'Kazakhstan' => ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe'],
    'Kenya' => ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
    'Kiribati' => ['Tarawa', 'Betio', 'Bikenibeu', 'Teaoraereke', 'Bairiki'],
    'Kuwait' => ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Al Farwaniyah', 'Al Jahra'],
    'Kyrgyzstan' => ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok'],
    'Laos' => ['Vientiane', 'Pakse', 'Savannakhet', 'Luang Prabang', 'Xam Neua'],
    'Latvia' => ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala'],
    'Lebanon' => ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Zahle'],
    'Lesotho' => ['Maseru', 'Teyateyaneng', 'Mafeteng', 'Hlotse', 'Mohale\'s Hoek'],
    'Liberia' => ['Monrovia', 'Gbarnga', 'Buchanan', 'Ganta', 'Kakata'],
    'Libya' => ['Tripoli', 'Benghazi', 'Misrata', 'Bayda', 'Zawiya'],
    'Liechtenstein' => ['Vaduz', 'Schaan', 'Triesen', 'Balzers', 'Eschen'],
    'Lithuania' => ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
    'Luxembourg' => ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Ettelbruck'],
    'Madagascar' => ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa', 'Mahajanga'],
    'Malawi' => ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Kasungu'],
    'Malaysia' => ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru', 'Malacca City', 'Kota Kinabalu', 'Kuantan', 'Kuching', 'Seremban'],    'Maldives' => ['Malé', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo'],
    'Mali' => ['Bamako', 'Sikasso', 'Kalabancoro', 'Koutiala', 'Ségou'],
    'Malta' => ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Zabbar'],
    'Marshall Islands' => ['Majuro', 'Ebeye', 'Arno', 'Jabor', 'Wotje'],
    'Mauritania' => ['Nouakchott', 'Nouadhibou', 'Kiffa', 'Kaédi', 'Rosso'],
    'Mauritius' => ['Port Louis', 'Vacoas-Phoenix', 'Beau Bassin-Rose Hill', 'Curepipe', 'Quatre Bornes'],
    'Mexico' => ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Zapopan'],
    'Micronesia' => ['Palikir', 'Weno', 'Kolonia', 'Tofol', 'Colonia'],
    'Moldova' => ['Chișinău', 'Bălți', 'Tiraspol', 'Bender', 'Rîbnița'],
    'Monaco' => ['Monaco', 'Monte Carlo', 'La Condamine', 'Fontvieille'],
    'Mongolia' => ['Ulaanbaatar', 'Erdenet', 'Darkhan', 'Choibalsan', 'Mörön'],
    'Montenegro' => ['Podgorica', 'Nikšić', 'Pljevlja', 'Bijelo Polje', 'Cetinje'],
    'Morocco' => ['Casablanca', 'Rabat', 'Fes', 'Marrakesh', 'Tangier', 'Agadir', 'Meknes', 'Oujda'],
    'Mozambique' => ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'],
    'Myanmar' => ['Yangon', 'Mandalay', 'Naypyidaw', 'Mawlamyine', 'Bago'],
    'Namibia' => ['Windhoek', 'Rundu', 'Walvis Bay', 'Swakopmund', 'Oshakati'],
    'Nauru' => ['Yaren', 'Denigomodu', 'Meneng', 'Aiwo', 'Boe'],
    'Nepal' => ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Bharatpur'],
    'Netherlands' => ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen'],    'New Zealand' => ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'],
    'Nicaragua' => ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega'],
    'Niger' => ['Niamey', 'Maradi', 'Zinder', 'Tahoua', 'Agadez'],
    'Nigeria' => ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria'],
    'North Korea' => ['Pyongyang', 'Hamhung', 'Chongjin', 'Nampo', 'Wonsan'],
    'North Macedonia' => ['Skopje', 'Bitola', 'Kumanovo', 'Prilep', 'Tetovo'],
    'Norway' => ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen'],
    'Oman' => ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar'],
    'Pakistan' => [
        'Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala',
        'Peshawar', 'Multan', 'Saidu Sharif', 'Hyderabad City', 'Islamabad',
        'Quetta', 'Bahawalpur', 'Sargodha', 'Sialkot', 'Sukkur',
        'Larkana', 'Chiniot', 'Shekhupura', 'Jhang', 'Dera Ghazi Khan',
        'Gujrat', 'Rahim Yar Khan', 'Kasur', 'Mardan', 'Mingaora',
        'Nawabshah', 'Sahiwal', 'Mirpur Khas', 'Okara', 'Mandi Bahauddin',
    ],    'Palau' => ['Ngerulmud', 'Koror', 'Airai', 'Kloulklubed', 'Meyuns'],
    'Panama' => ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'Arraiján'],
    'Papua New Guinea' => ['Port Moresby', 'Lae', 'Arawa', 'Mount Hagen', 'Popondetta'],
    'Paraguay' => ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'],
    'Peru' => ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura'],
    'Philippines' => ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga City', 'Taguig', 'Pasig', 'Cagayan de Oro'],
    'Poland' => ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'],
    'Portugal' => ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora', 'Braga'],
    'Qatar' => ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal'],
    'Romania' => ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța'],
    'Russia' => ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Omsk', 'Rostov-on-Don', 'Ufa'],    'Rwanda' => ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri', 'Gisenyi'],
    'Saint Kitts and Nevis' => ['Basseterre', 'Charlestown', 'Sadlers', 'Cayon', 'Sandy Point Town'],
    'Saint Lucia' => ['Castries', 'Gros Islet', 'Vieux Fort', 'Soufrière', 'Dennery'],
    'Saint Vincent and the Grenadines' => ['Kingstown', 'Georgetown', 'Byera Village', 'Biabou', 'Port Elizabeth'],
    'Samoa' => ['Apia', 'Vaitele', 'Faleasiu', 'Vailele', 'Leauva\'a'],
    'San Marino' => ['San Marino', 'Serravalle', 'Borgo Maggiore', 'Domagnano', 'Fiorentino'],
    'Sao Tome and Principe' => ['São Tomé', 'Trindade', 'Santana', 'Neves', 'Guadalupe'],
    'Saudi Arabia' => ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Ta\'if', 'Tabuk', 'Buraydah', 'Khamis Mushait', 'Abha', 'Al Khobar'],    'Senegal' => ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Kaolack'],
    'Serbia' => ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
    'Seychelles' => ['Victoria', 'Anse Boileau', 'Bel Ombre', 'Beau Vallon', 'Cascade'],
    'Sierra Leone' => ['Freetown', 'Bo', 'Kenema', 'Makeni', 'Koidu Town'],
    'Singapore' => ['Singapore'],
    'Slovakia' => ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica'],
    'Slovenia' => ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje'],
    'Solomon Islands' => ['Honiara', 'Gizo', 'Auki', 'Noro', 'Kirakira'],
    'Somalia' => ['Mogadishu', 'Hargeisa', 'Bosaso', 'Galkayo', 'Berbera'],
    'South Africa' => ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Nelspruit', 'Kimberley', 'Polokwane'],    'South Korea' => ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan'],
    'South Sudan' => ['Juba', 'Wau', 'Malakal', 'Yambio', 'Torit'],
    'Spain' => ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma'],
    'Sri Lanka' => ['Colombo', 'Dehiwala-Mount Lavinia', 'Moratuwa', 'Sri Jayawardenepura Kotte', 'Negombo'],
    'Sudan' => ['Khartoum', 'Omdurman', 'Khartoum North', 'Nyala', 'Port Sudan'],
    'Suriname' => ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie', 'Moengo', 'Meerzorg'],
    'Sweden' => ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'],
    'Switzerland' => ['Zürich', 'Geneva', 'Basel', 'Lausanne', 'Bern'],
    'Syria' => ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
    'Taiwan' => ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Taoyuan'],
    'Tajikistan' => ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar', 'Istaravshan'],
    'Tanzania' => ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya'],
    'Thailand' => ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai', 'Hat Yai'],
    'Timor-Leste' => ['Dili', 'Baucau', 'Maliana', 'Suai', 'Likisá'],
    'Togo' => ['Lomé', 'Sokodé', 'Kara', 'Kpalimé', 'Atakpamé'],
    'Tonga' => ['Nuku\'alofa', 'Neiafu', 'Haveluloto', 'Vaini', 'Tofoa-Koloa'],
    'Trinidad and Tobago' => ['Port of Spain', 'Chaguanas', 'San Fernando', 'Arima', 'Point Fortin'],
    'Tunisia' => ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan'],
    'Turkey' => ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Antalya', 'Konya', 'Kayseri', 'Mersin', 'Eskisehir', 'Diyarbakir'],    'Turkmenistan' => ['Ashgabat', 'Türkmenabat', 'Daşoguz', 'Mary', 'Balkanabat'],
    'Tuvalu' => ['Funafuti', 'Savave Village', 'Motufoua', 'Teava', 'Lofeagai'],
    'Uganda' => ['Kampala', 'Nansana', 'Kira', 'Ssabagabo', 'Mbarara'],
    'Ukraine' => ['Kyiv', 'Kharkiv', 'Odesa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv'],
    'United Arab Emirates' => ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain'],
    'United Kingdom' => ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Leeds', 'Liverpool', 'Newcastle', 'Sheffield', 'Bristol', 'Edinburgh', 'Leicester', 'Coventry', 'Cardiff', 'Belfast'],
    'United States' => [
        'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
        'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose',
        'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'San Francisco',
        'Charlotte', 'Indianapolis', 'Seattle', 'Denver', 'Washington',
        'Boston', 'El Paso', 'Nashville', 'Detroit', 'Oklahoma City',
        'Portland', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore',
    ],
    'Uruguay' => ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras'],
    'Uzbekistan' => ['Tashkent', 'Samarkand', 'Namangan', 'Andijan', 'Nukus'],
    'Vanuatu' => ['Port Vila', 'Luganville', 'Norsup', 'Port-Olry', 'Isangel'],
    'Venezuela' => ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Ciudad Guayana'],
    'Vietnam' => ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Bien Hoa'],
    'Yemen' => ['Sanaa', 'Aden', 'Taiz', 'Al Hudaydah', 'Ibb'],
    'Zambia' => ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Chingola'],
    'Zimbabwe' => ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Epworth'],
];
